### ISSUE TITLE
无法正常使用无尽存储

### ISSUE THREAD

**Issue by humonia-sys** [SlimefunGuguProject/InfinityExpansion#26]
### 检查项目

- [X] 你使用的是从构建站下载的版本 (https://builds.guizhanss.net)
- [X] 你已经检验过下载的文件的校验和，确认已完整下载文件 (暂未推出)
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你没有安装`CS-CoreLib`
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/InfinityExpansion/issues)，且没有找到相同的问题

### 问题描述

不正常关服/重启有几率使存储核心失效,变为普通的原木

### 复现步骤

1.使用存储核心
2.开开关关服务器

### 预期行为

正常使用

### 服务器日志

https://paste.guizhanss.net/kvAr5

### 服务端软件

Paper

### Minecraft 版本

1.19.x

### CS-CoreLib 版本

- [X] 我没有安装CS-CoreLib

### Slimefun版本

![图片](https://github.com/SlimefunGuguProject/InfinityExpansion/assets/85441099/34631ca0-7fe3-4d63-9655-1a419781ae56)

### 插件版本

11

**Comment by humonia-sys** [comment]
Minecraft版本为1.20.2, 没有1.20.x的选项

**Comment by humonia-sys** [comment]
补充: 即使打掉橡木重新放也无法恢复原有功能

**Comment by JiangQiYan713** [comment]
遇到了相同的问题 表现为初次打开存储时显示输出栏只有一个原有物品，并且不表示被存储物品的类型
如图
![image](https://github.com/SlimefunGuguProject/InfinityExpansion/assets/91627081/ec228b46-2610-497d-9d6f-33fdc5f1b3d0)

打开存储不会报错
挖掉存储会报错，并且什么也不会掉落

以下是后台报错，与[#27](https://github.com/SlimefunGuguProject/InfinityExpansion/issues/27)的报错相似
```
[05:07:07] [Server thread/ERROR]: [InfinityExpansion] Item "INFINITY_STORAGE" from InfinityExpansion vBuild 11 (git f9fe427) has caused an Error!
[05:07:07] [Server thread/ERROR]: [InfinityExpansion] You can report it here: https://github.com/SlimefunGuguProject/InfinityExpansion/issues
[05:07:07] [Server thread/ERROR]: [InfinityExpansion] Could not pass "BlockBreakHandler" for StorageUnit - 'INFINITY_STORAGE' (InfinityExpansion vBuild 11 (git f9fe427))
java.lang.IllegalArgumentException: The provided value cannot be null
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-32.1.2-jre.jar:?]
	at org.bukkit.craftbukkit.v1_20_R2.persistence.CraftPersistentDataContainer.set(CraftPersistentDataContainer.java:39) ~[paper-1.20.2.jar:git-Paper-241]
	at io.github.mooy1.infinityexpansion.items.storage.StorageUnit.saveToStack(StorageUnit.java:214) ~[InfinityExpansion-Build 11 (git f9fe427).jar:?]
	at io.github.mooy1.infinityexpansion.items.storage.StorageCache.destroy(StorageCache.java:257) ~[InfinityExpansion-Build 11 (git f9fe427).jar:?]
	at io.github.mooy1.infinityexpansion.items.storage.StorageUnit$2.onPlayerBreak(StorageUnit.java:116) ~[InfinityExpansion-Build 11 (git f9fe427).jar:?]
	at io.github.thebusybiscuit.slimefun4.implementation.listeners.BlockListener.lambda$callBlockHandler$3(BlockListener.java:215) ~[slimefun-23.10.16-release.jar:?]
	at io.github.thebusybiscuit.slimefun4.api.items.SlimefunItem.callItemHandler(SlimefunItem.java:1002) ~[slimefun-23.10.16-release.jar:?]
	at io.github.thebusybiscuit.slimefun4.implementation.listeners.BlockListener.callBlockHandler(BlockListener.java:215) ~[slimefun-23.10.16-release.jar:?]
	at io.github.thebusybiscuit.slimefun4.implementation.listeners.BlockListener.onBlockBreak(BlockListener.java:188) ~[slimefun-23.10.16-release.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor38.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:git-Paper-241]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.2.jar:git-Paper-241]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.2.jar:git-Paper-241]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:378) ~[?:?]
	at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:337) ~[?:?]
	at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:215) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1819) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:42) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:15) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:53) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.2.jar:git-Paper-241]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1324) ~[paper-1.20.2.jar:git-Paper-241]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193) ~[paper-1.20.2.jar:git-Paper-241]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1301) ~[paper-1.20.2.jar:git-Paper-241]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1294) ~[paper-1.20.2.jar:git-Paper-241]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1272) ~[paper-1.20.2.jar:git-Paper-241]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1160) ~[paper-1.20.2.jar:git-Paper-241]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-241]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

```

**Comment by JiangQiYan713** [comment]
创造模式以及使用扳手拆除，不会掉落
生存模式打掉，会掉落一个原版的橡木

**Comment by JiangQiYan713** [comment]
Slimefun 运行的服务器环境:
Paper git-Paper-241 (MC: 1.20.2)
Slimefun 23.10.16-release
Metrics-组件 #28
Java 17

安装的附属插件: (19)
  Networks vBuild 84 (git 8dfde04)
  DyedBackpacks vBuild 3 (git d4e0e45)
  GuizhanLibPlugin vBuild 34 (git 7be8d2b)
  ExtraTools vBuild 6 (git 204b2a5)
  FoxyMachines vBuild 26 (git cb02352)
  SfChunkInfo vBuild 9 (git 1be8703)
  Residence v5.1.4.0
  ExoticGarden vBuild 15 zh-CN(ybw0014) (git 1aa87ca)
  SlimeHUD vBuild 10 (git 1e67ac2)
  InfinityExpansion vBuild 11 (git f9fe427)
  SlimeCustomizer vBuild 26 zh-CN(SlimefunGuguProject) (git 5115d68)
  SlimeGlue vBuild 23 (git 04c4247)
  SimpleUtils vBuild 2 (git f774b8d)
  VillagerUtil vBuild 2 zh-CN(ybw0014) (git f019674)
  MobCapturer vBuild 15 (git cc3a3c5)
  SlimeTinker vBuild 48 (git 020a5f4)
  TranscEndence vBuild 6 zh-CN(baoad) (git 12c5713)
  ColoredEnderChests vBuild 4 (git c99f079)
  FluffyMachines vBuild 25 (git 9bca1f2)

**Comment by hed516** [comment]
遇到一样的问题
[10:17:32 ERROR]: [Slimefun] An exception thrown while handling the click: 
java.lang.NullPointerException: Cannot invoke "org.bukkit.Material.getMaxStackSize()" because "this.material" is null
        at io.github.mooy1.infinityexpansion.items.storage.StorageCache.withdraw(StorageCache.java:444) ~[S_[无尽科技]InfinityExpansion11_hed-fix2.jar:?]
        at io.github.mooy1.infinityexpansion.items.storage.StorageCache.lambda$new$2(StorageCache.java:161) ~[S_[无尽科技]InfinityExpansion11_hed-fix2.jar:?]
        at me.mrCookieSlime.CSCoreLibPlugin.general.Inventory.MenuListener.onClick(MenuListener.java:59) ~[Slimefun-1e05b50-Beta.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor262.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-196]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-196]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3237) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1338) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1315) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1308) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1286) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[10:17:33 ERROR]: [Slimefun] An exception thrown while handling the click: 
java.lang.NullPointerException: Cannot invoke "org.bukkit.Material.getMaxStackSize()" because "this.material" is null
        at io.github.mooy1.infinityexpansion.items.storage.StorageCache.lambda$new$2(StorageCache.java:153) ~[S_[无尽科技]InfinityExpansion11_hed-fix2.jar:?]
        at me.mrCookieSlime.CSCoreLibPlugin.general.Inventory.MenuListener.onClick(MenuListener.java:59) ~[Slimefun-1e05b50-Beta.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor262.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-196]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-196]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3237) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1338) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1315) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1308) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1286) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[10:17:33 ERROR]: [Slimefun] An exception thrown while handling the click: 
java.lang.NullPointerException: Cannot invoke "org.bukkit.Material.getMaxStackSize()" because "this.material" is null
        at io.github.mooy1.infinityexpansion.items.storage.StorageCache.lambda$new$2(StorageCache.java:153) ~[S_[无尽科技]InfinityExpansion11_hed-fix2.jar:?]
        at me.mrCookieSlime.CSCoreLibPlugin.general.Inventory.MenuListener.onClick(MenuListener.java:59) ~[Slimefun-1e05b50-Beta.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor262.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-196]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-196]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3237) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1338) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1315) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1308) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1286) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[10:17:36 ERROR]: [InfinityExpansion] Item "ADVANCED_STORAGE" from InfinityExpansion vUNOFFICIAL has caused an Error!
[10:17:36 ERROR]: [InfinityExpansion] You can report it here: https://github.com/SlimefunGuguProject/InfinityExpansion/issues
[10:17:36 ERROR]: [InfinityExpansion] Could not pass "BlockBreakHandler" for StorageUnit - 'ADVANCED_STORAGE' (InfinityExpansion vUNOFFICIAL)
java.lang.IllegalArgumentException: The provided value cannot be null
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.1-jre.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.persistence.CraftPersistentDataContainer.set(CraftPersistentDataContainer.java:39) ~[paper-1.20.1.jar:git-Paper-196]
        at io.github.mooy1.infinityexpansion.items.storage.StorageUnit.saveToStack(StorageUnit.java:214) ~[S_[无尽科技]InfinityExpansion11_hed-fix2.jar:?]
        at io.github.mooy1.infinityexpansion.items.storage.StorageCache.destroy(StorageCache.java:257) ~[S_[无尽科技]InfinityExpansion11_hed-fix2.jar:?]
        at io.github.mooy1.infinityexpansion.items.storage.StorageUnit$2.onPlayerBreak(StorageUnit.java:116) ~[S_[无尽科技]InfinityExpansion11_hed-fix2.jar:?]
        at io.github.thebusybiscuit.slimefun4.implementation.listeners.BlockListener.lambda$callBlockHandler$3(BlockListener.java:228) ~[Slimefun-1e05b50-Beta.jar:?]
        at io.github.thebusybiscuit.slimefun4.api.items.SlimefunItem.callItemHandler(SlimefunItem.java:1003) ~[Slimefun-1e05b50-Beta.jar:?]
        at io.github.thebusybiscuit.slimefun4.implementation.listeners.BlockListener.callBlockHandler(BlockListener.java:228) ~[Slimefun-1e05b50-Beta.jar:?]
        at io.github.thebusybiscuit.slimefun4.implementation.listeners.BlockListener.onBlockBreak(BlockListener.java:198) ~[Slimefun-1e05b50-Beta.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor278.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-196]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-196]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:378) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:337) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:301) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1927) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:42) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:15) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1338) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1315) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1308) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1286) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by ybw0014** [comment]
把有可能造成这两个报错的地方修了一下，但是至于存储的物品丢失问题就暂时不清楚如何复现
